"""empty message

Revision ID: bc7a31884dcc
Revises: 
Create Date: 2019-10-17 03:41:12.483578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7a31884dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crouse',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crouse_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crouse_crouse_name'), 'crouse', ['crouse_name'], unique=True)
    op.create_table('xclass',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('student',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=20), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['xclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=True)
    op.create_table('tags',
    sa.Column('crouse_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crouse_id'], ['crouse.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('crouse_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_table('xclass')
    op.drop_index(op.f('ix_crouse_crouse_name'), table_name='crouse')
    op.drop_table('crouse')
    # ### end Alembic commands ###
