"""empty message

Revision ID: 9d147c41d691
Revises: a833605d812b
Create Date: 2019-04-08 04:51:13.712129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d147c41d691'
down_revision = 'a833605d812b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=True),
    sa.Column('s_age', sa.Integer(), nullable=True),
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['g_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('grade')
    # ### end Alembic commands ###
