"""empty message

Revision ID: 00df0da21d97
Revises: c56e31e3eeea
Create Date: 2020-01-19 22:51:11.882413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00df0da21d97'
down_revision = 'c56e31e3eeea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'from_admin')
    op.drop_column('reply', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('author', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('reply', sa.Column('from_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
