"""empty message

Revision ID: 254e9e3bd0f5
Revises: 00df0da21d97
Create Date: 2020-01-19 22:54:19.439875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '254e9e3bd0f5'
down_revision = '00df0da21d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reply_ibfk_2', 'reply', type_='foreignkey')
    op.drop_column('reply', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('reply_ibfk_2', 'reply', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
