"""empty message

Revision ID: c56e31e3eeea
Revises: 5d6cad6ae670
Create Date: 2020-01-19 22:43:42.842957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c56e31e3eeea'
down_revision = '5d6cad6ae670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_table('message')
    op.drop_column('comment', 'author')
    op.drop_column('comment', 'from_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('from_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('author', mysql.VARCHAR(length=30), nullable=True))
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('from_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reply_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['message.id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###
