"""empty message

Revision ID: ff2919be654e
Revises: e8cad27e9a52
Create Date: 2019-11-19 04:45:47.171808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff2919be654e'
down_revision = 'e8cad27e9a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'class17', ['class_num'])
    op.add_column('s_t', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_constraint('s_t_ibfk_1', 's_t', type_='foreignkey')
    op.create_foreign_key(None, 's_t', 'student', ['student_id'], ['id'])
    op.drop_column('s_t', 'class17_id')
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('class_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'class17', ['class_id'], ['id'])
    op.add_column('s_t', sa.Column('class17_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 's_t', type_='foreignkey')
    op.create_foreign_key('s_t_ibfk_1', 's_t', 'class17', ['class17_id'], ['id'])
    op.drop_column('s_t', 'student_id')
    op.drop_constraint(None, 'class17', type_='unique')
    # ### end Alembic commands ###
